name: Pull Request
description: Create a pull request
title: ""
labels: ["contributor"]
body:
  - type: markdown
    attributes:
      value: |
        ## Hello Axolotl!
        **Thank you for contributing to the lakeFS project.**
        We appreciate the time invested in this pull request and created this template to help make this process easier.
        It's really important to have all the information and context, to ensure we can properly address this PR 
        Please use the following references to fill out the pull request.
        
  - type: input
    id: linked-issue
    attributes:
      label: Linked Issue
      description: Issue closed by this PR
      value: Closes #
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Change Description
      description: Also tell us, what did you expect to happen?
      value: |  
        Bug Fix:
        How was it fixed - describe the solution
      
        New Feature:
        Description of new feature
      
        Testing Details:
        How were the changes tested?
        Added new unit tests / integration tests
      
        Add screenshots if applicable (CLI / GUI changes)
      validations:
      required: true
      
  - type: input
    id: lakefs_version
    attributes:
      label: lakeFS Version
      description: What version of lakeFS are you running?

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs output and screenshots
      description: Please copy and paste any relevant log output (lakeFS, clients, ecosystem). Make sure to scrub anything confidential! These will typically be near strings such as `secret`, `access` or `AKIA`
      render: shell
      
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
